
model_name_or_path: /home/users/nus/e0846828/scratch/fsdrive/models/Qwen2.5-VL-7B-Instruct
trust_remote_code: true

enable_liger_kernel: true
use_unsloth_gc: true
flash_attn: fa2


stage: sft          
do_train: true
finetuning_type: full 
freeze_vision_tower: true
freeze_multi_modal_projector: true

dataset:
  - toy_debug       
#  - train_cot_motion_clean
dataset_dir: /home/users/nus/e0846828/FSDrive/LLaMA-Factory/data
cache_dir: /home/users/nus/e0846828/scratch/fsdrive/cache/pretrain_run_clean1
overwrite_cache: true

template: qwen2_vl
cutoff_len: 32768
max_new_tokens: 2048
max_samples: 10000000
preprocessing_num_workers: 16

output_dir: /home/users/nus/e0846828/scratch/fsdrive/saves/qwen2_5_vl/pretrain
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true


per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-4
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000


temperature: 0.1
top_p: 0.1
top_k: 10

skip_special_tokens: false

